import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import * as fns from "date-fns";
import { ru } from "date-fns/locale";

fns.setDefaultOptions({ locale: ru });

const inter = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Hairdresser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
